module.exports = {
  extends: [
    "airbnb",
    "airbnb/hooks",
    "plugin:flowtype/recommended",
    "plugin:prettier/recommended",
    "prettier/flowtype",
    "prettier/react"
  ],
  parser: "babel-eslint",
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: 6,
    sourceType: "module"
  },
  plugins: [
    "flowtype",
    "immutable",
    "import",
    "jsx-a11y",
    "prettier",
    "react-hooks",
    "react",
    "sorting"
  ],
  rules: {
    "flowtype/generic-spacing": "off",
    "flowtype/space-after-type-colon": "off",
    "immutable/no-let": "off",
    "immutable/no-mutation": "off",
    "import/extensions": "off",
    "import/newline-after-import": "off",
    "import/no-cycle": "off",
    "import/no-extraneous-dependencies": "off",
    "import/no-named-as-default": "off",
    "import/no-named-default": "off",
    "import/prefer-default-export": "off",
    "jsx-a11y/alt-text": "off",
    "jsx-a11y/anchor-has-content": "off",
    "jsx-a11y/anchor-is-valid": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/control-has-associated-label": "off",
    "jsx-a11y/iframe-has-title": "off",
    "jsx-a11y/interactive-supports-focus": "off",
    "jsx-a11y/label-has-associated-control": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off",
    "jsx-a11y/no-noninteractive-element-to-interactive-role": "off",
    "jsx-a11y/no-noninteractive-tabindex": "off",
    "jsx-a11y/no-redundant-roles": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "prettier/prettier": ["error"],
    "react/button-has-type": "off",
    "react/default-props-match-prop-types": "off",
    "react/destructuring-assignment": "off",
    "react/jsx-closing-tag-location": "off",
    "react/jsx-curly-brace-presence": "off",
    "react/jsx-curly-newline": "off",
    "react/jsx-filename-extension": "off",
    "react/jsx-no-comment-textnodes": "off",
    "react/jsx-no-target-blank": "off",
    "react/jsx-one-expression-per-line": "off",
    "react/jsx-props-no-spreading": "off",
    "react/jsx-wrap-multilines": "off",
    "react/no-access-state-in-setstate": "off",
    "react/no-array-index-key": "off",
    "react/no-danger": "off",
    "react/no-find-dom-node": "off",
    "react/no-string-refs": "off",
    "react/no-unescaped-entities": "off",
    "react/no-unused-prop-types": "off",
    "react/no-will-update-set-state": "off",
    "react/prefer-stateless-function": "off",
    "react/prop-types": "off",
    "react/require-default-props": "off",
    "react/sort-comp": "off",
    "react/state-in-constructor": "off",
    "react/static-property-placement": "off",
    "sorting/sort-object-props": "off",
    "array-callback-return": "off",
    camelcase: "off",
    "class-methods-use-this": "off",
    "func-names": "off",
    "global-require": "off",
    "lines-between-class-members": "off",
    "max-classes-per-file": "off",
    "no-async-promise-executor": "off",
    "no-bitwise": "off",
    "no-case-declarations": "off",
    "no-continue": "off",
    "no-empty-pattern": "off",
    "no-extra-boolean-cast": "off",
    "no-lonely-if": "off",
    "no-multi-assign": "off",
    "no-param-reassign": "off",
    "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
    "no-prototype-builtins": "off",
    "no-restricted-globals": "off",
    "no-restricted-properties": "off",
    "no-restricted-syntax": "off",
    "no-return-await": "off",
    "no-underscore-dangle": "off",
    "no-unneeded-ternary": "off",
    "no-unsafe-finally": "off",
    "no-unused-expressions": "off",
    "no-unused-vars": "off",
    "no-useless-computed-key": "off",
    "no-useless-escape": "off",
    "no-useless-return": "off",
    "prefer-destructuring": "off",
    "prefer-promise-reject-errors": "off",
    "prefer-spread": "off",
    "prefer-template": "off",
    radix: "off",
    "spaced-comment": "off",
    "valid-typeof": "off"
  },
  env: {
    browser: true,
    es6: true,
    jquery: true,
    node: true
  },
  globals: {
    _context: true,
    $Diff: false,
    $ElementType: true,
    $Keys: false,
    $PropertyType: false,
    $Shape: false,
    $Values: true,
    ActiveXObject: false,
    before: false,
    beforeEach: false,
    Class: false,
    context: false,
    cy: false,
    Cypress: false,
    describe: false,
    expect: false,
    express$Middleware: false,
    express$NextFunction: false,
    express$Request: false,
    express$Response: false,
    FB: false,
    ga: false,
    Generator: false,
    GeocoderAddressComponent: false,
    GeocoderGeometry: false,
    GeocoderLocationType: false,
    GeocoderRequest: false,
    GeocoderResult: false,
    GeocoderStatus: false,
    google: false,
    intlTelInputUtils: false,
    it: false,
    jest: false,
    LatLngBoundsLiteral: false,
    LatLngLiteral: false,
    loadImage: false,
    PlaceAspectRating: false,
    PlaceGeometry: false,
    PlaceResult: false,
    Raven: false,
    React$Element: false,
    ReactClass: false,
    ReactComponent: false,
    ReactElement: false,
    RequestOptions: false,
    Royalslider: false,
    ScalarPoiKinds: false,
    SyntheticClipboardEvent: false,
    SyntheticCompositionEvent: false,
    SyntheticDragEvent: false,
    SyntheticEvent: false,
    SyntheticFocusEvent: false,
    SyntheticInputEvent: false,
    SyntheticKeyboardEvent: false,
    SyntheticMouseEvent: false,
    SyntheticTouchEvent: false,
    SyntheticUIEvent: false,
    SyntheticWheelEvent: false,
    test: false,
    TimeoutID: false,
    WOW: false
  }
};
